'use client'

import {
  Accordion,
  AccordionButton,
  AccordionIcon,
  AccordionItem,
  AccordionPanel,
  Alert,
  AlertDescription,
  AlertIcon,
  AlertTitle,
  Box,
  Button,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Flex,
  Heading,
  Link,
  ListItem,
  Stack,
  Text,
  UnorderedList,
  useColorModeValue,
} from '@chakra-ui/react'
import Image from 'next/image'

import DashboardImage from './morpheus-dashboard.png'

import { type ICtaSectionFields } from '@/@types/generated/contentful'
import { CTABlock } from '@/components/cta-block'
import { PageContainer } from '@/components/page-container'

const CtaSectionFields = {
  title: 'MOR Token Claim is LIVE Now',
  body: 'Capital and Coders can now claim MOR rewards',
  primaryButtonLink: 'https://dashboard.mor.org/#/mainnet/capital',
  primaryButtonText: 'Claim MOR',
  primaryIsExternal: true,
} as ICtaSectionFields

const data = [
  {
    group: 'Claim Day Related Questions',
    items: [
      {
        question: 'What will happen on May 8th 2024?',
        answer:
          'On this day, AMM liquidity will be deployed and MOR token will become available for claiming and trading.',
      },
      { question: 'At what time is the TGE?', answer: 'It’s at 12:00 UTC on May 8th.' },
      { question: 'On which network will the MOR token be?', answer: 'It’s Arbitrum mainnet.' },
      {
        question:
          'On which decentralized exchange will the listing occur and in which trading pair?',
        answer: 'Uniswap, wETH/MOR',
      },
      {
        question: 'How to buy MOR?',
        answer:
          'You can buy MOR on the Uniswap exchange on the Arbitrum chain. The guidance will be shared before the launch.',
      },
      {
        question: 'Can I buy MOR if I don’t have wETH, but ETH and USDC?',
        answer:
          'Yes, you can buy the token using any liquid token available on the Uniswap exchange. In this case, your token will be exchanged for wETH and then for MOR.',
      },
      {
        question: 'When will Morpheus be listed on centralized exchanges, like Binance?',
        answer:
          'It’s best to ask the exchange representatives directly as they make the listing decisions.',
      },
      {
        question: 'What is the MOR circulating supply?',
        answer:
          'The circulating supply on May 8th is ~1,300,000 MOR, but only 624,000 MOR rewards for Capital and Code contributors will be available for claim, as Compute and Community parts are not live yet.',
      },
      {
        question: 'What is the MOR total supply?',
        answer: '42,000,000 tokens that will be released over 16 years.',
      },
      {
        question: 'How much liquidity in wETH will be added?',
        answer: 'Approximately 880 wETH based on preliminary calculations.',
      },
      {
        question: 'How will initial liquidity be deployed?',
        answer:
          'For the initial liquidity deployment, a phased approach will be used. More details can be found in this document: https://github.com/MorpheusAIs/Docs/blob/main/!KEYDOCS%20README%20FIRST!/Phased%20AMM%20Deployment%20and%20Fair%20Price%20Discovery.md',
      },
      {
        question: 'How will token liquidity be maintained in the future?',
        answer:
          'Morpheus will use half of the yield generated by Capital Providers to buy back MOR from the open market, combine it with the remaining wETH, and add it to the liquidity.',
      },
      {
        question: 'What is Protocol Owned Liquidity (PoL)?',
        answer:
          "It's liquidity that is owned and controlled by the protocol itself, rather than by individual liquidity providers. This helps ensure the protocol's long-term sustainability and independence.",
      },
      {
        question: 'Can May 8th 2024 be considered as the Morpheus launch?',
        answer:
          'Not exactly, as the Morpheus software has been live since 2023, the MOR token was fair launched on February 8th, 2024, and for 90 days accumulated liquidity generated by Capital Providers. These Contributor addresses are used to record who can claim MOR tokens on May 8th 2024.',
      },
    ],
  },
  {
    group: 'MOR TOKEN RELATED QUESTIONS',
    items: [
      { question: 'What is MOR?', answer: 'MOR is the underlying token of the Morpheus network.' },
      {
        question: 'What is the utility of MOR?',
        answer:
          'The main utility of the MOR token is access to the network compute resources for holders and rewards for ecosystem contributors. You will also be able to stake MOR towards frontends and smart agents you like, thereby directing community emissions to them and be rewarded in their native tokens. Additionally, MOR will be the main asset for AI projects launched in the Morpheus ecosystem, like ETH for Ethereum. Finally, all settlements between parties are also in MOR.',
      },
      {
        question: 'Was there a presale, and what is the vesting schedule?',
        answer:
          'There was no presale, premine or any type of token allocations as it’s a fair launch.',
      },
      {
        question: 'What is a fair launch?',
        answer:
          "It's a method of launching the Morpheus project with equal conditions for all participants, without premine and allocations for the team, founders, investors, etc. MOR tokens can only be earned or purchased.",
      },
    ],
  },
  {
    group: 'CONTRIBUTORS RELATED QUESTIONS',
    items: [
      {
        question: 'How can I claim my rewards?',
        answer:
          'You will need to visit the website https://dashboard.mor.org and click on the "Claim MOR" button, which will become active after 12:00 UTC on May 8th. A step-by-step guide will be published before the launch for your convenience.',
      },
      {
        question: 'Do I have to pay fees?',
        answer:
          'Yes, since the claim transaction is generated on the Ethereum blockchain, and the MOR rewards will be received on the Arbitrum chain.',
      },
      {
        question: 'How quickly will I receive my tokens?',
        answer:
          'After confirming the claim transaction, you will receive your tokens within a few minutes.',
      },
      {
        question: 'Do I need to withdraw my stETH deposit after May 8th?',
        answer: 'No, you can continue staking and receiving rewards.',
      },
      {
        question: 'Can I make a deposit after May 8th?',
        answer:
          'Yes, emissions of rewards for Capital Providers are an integral part of the protocol. The initial distribution curve will last for 16 years, with tail emissions after, for a total of at least 256 years.',
      },
      {
        question: 'Do I need to claim MOR on May 8th, or can I leave it unclaimed for 2 months?',
        answer:
          'You can leave your rewards unclaimed; nothing will happen to them as they will be stored in the contract until you decide to claim them.',
      },
      {
        question: 'Do I lose earned MOR rewards if I decide to withdraw stETH?',
        answer:
          'No, you don’t lose them, but you will no longer earn rewards as you are no longer a Capital Provider.',
      },
      {
        question: 'Where can I check my MOR earnings?',
        answer:
          'You can see them at https://dashboard.mor.org/#/ when connecting a depositing wallet.',
      },
      {
        question: 'How many MOR tokens can I get by depositing 1 stETH?',
        answer:
          'It is a dynamic value that depends on the ratio of your contribution to the total amount of deposited stETH. You can check it at https://morstats.info/staked_eth/',
      },
      {
        question: 'Is there a minimum or maximum amount of MOR I can claim?',
        answer: 'There are no limitations; you can claim any amount.',
      },
      {
        question: 'Are there any limitations for MOR claims, like token lock or vesting?',
        answer: 'No, there are no limitations.',
      },
      {
        question: 'How often are rewards distributed?',
        answer:
          'The MOR token is accrued with every Ethereum block, meaning you can claim every 12 seconds, but each time you make a “Claim” transaction will need to pay a fee.',
      },
      {
        question: 'If I stake my stETH, do I get it back, or is it converted into MOR?',
        answer:
          'It’s not converted into MOR; you can get back the full amount of stETH you deposited after 7 days of the initial lockup.',
      },
      {
        question: 'Who should I contact if I encounter difficulties?',
        answer:
          'The community is always ready to provide support. Please describe your issue in the Discord support channel https://discord.com/channels/1151741790408429580/1183666837460897832',
      },
    ],
  },
]

export default function Home() {
  return (
    <PageContainer>
      <Heading textAlign='center' mb={4}>
        Overview of Morpheus Fair Launch
      </Heading>
      <Text fontSize='lg' textAlign='center' whiteSpace='pre-line'>
        {`Morpheus is designed to incentivize the first peer-to-peer network of personal general purpose AI, powered by the MOR token.`}
      </Text>
      <CTABlock fields={CtaSectionFields} containerProps={{ px: 0, py: 0, mt: 6 }} />
      <Stack gap={12} mt={6} maxWidth='container.md' mx='auto'>
        <Card
          borderWidth={1}
          borderColor={useColorModeValue('blackAlpha.100', 'whiteAlpha.50')}
          bg={useColorModeValue('blackAlpha.100', 'whiteAlpha.50')}
          backdropFilter='blur(10px)'
        >
          <CardHeader>
            <Image src={DashboardImage} alt='stuff' />
          </CardHeader>
          <CardBody fontSize='sm'>
            <UnorderedList spacing={2}>
              <ListItem>MOR Fair Launch started on Feb 8th 2024 at 12pm UTC</ListItem>
              <ListItem>
                Tokens start accruing from this time, but aren’t transferable for 90 days.
              </ListItem>
              <ListItem>The network itself is not yet live.</ListItem>
              <ListItem>
                Be careful of scammers
                <UnorderedList ml={5} mt={2}>
                  <ListItem>There is no airdrop</ListItem>
                  <ListItem>There is no token sale</ListItem>
                  <ListItem>There is no NFT</ListItem>
                </UnorderedList>
              </ListItem>
            </UnorderedList>
          </CardBody>
          <CardFooter
            gap={4}
            flexDir={{ base: 'column', md: 'row' }}
            alignItems={{ base: 'flex-start', md: 'center' }}
          >
            <Text fontWeight='bold'>To participate in fair launch, stake stETH here:</Text>
            <Button as={Link} isExternal href='https://dashboard.mor.org/'>
              Morpheus Dashboard
            </Button>
          </CardFooter>
        </Card>
        <Card
          borderWidth={1}
          borderColor={useColorModeValue('blackAlpha.100', 'whiteAlpha.50')}
          bg={useColorModeValue('blackAlpha.100', 'whiteAlpha.50')}
          backdropFilter='blur(10px)'
        >
          <Accordion borderWidth={0} defaultIndex={[0]}>
            <AccordionItem borderWidth={0}>
              <h2>
                <AccordionButton>
                  <Box as='span' flex='1' textAlign='left' fontWeight='bold'>
                    How does the staking work?
                  </Box>
                  <AccordionIcon />
                </AccordionButton>
              </h2>
              <AccordionPanel>
                <Stack spacing={6}>
                  <UnorderedList spacing={2} fontSize='sm'>
                    <ListItem>
                      Minimum staking deposit amount must be greater than 0.011 stETH
                    </ListItem>
                    <ListItem>
                      You stake stETH in the Morpheus contract (use above dashboard link)
                    </ListItem>
                    <ListItem>You can withdraw that stETH any time after 7 days. </ListItem>
                    <ListItem>
                      While it’s in the contract, the normal stETH yield from your stETH is given to
                      the Morpheus network. [this is what you lose]
                    </ListItem>
                    <ListItem>
                      In return, you earn a pro-rata share of the MOR emissions on an ongoing basis.
                      [this is what you gain]
                    </ListItem>
                    <ListItem>
                      MOR is a native Arbitrum token for cheaper txs, and the initial liquidity pool
                      will be Uniswap on Arbitrum.
                    </ListItem>
                  </UnorderedList>
                  <Flex
                    gap={4}
                    fontSize='sm'
                    borderWidth={1}
                    borderColor='whiteAlpha.300'
                    borderStyle='dashed'
                    p={4}
                  >
                    <Text fontWeight='bold'>Example</Text>
                    <Text>
                      If you deposit 1 stETH and 9 other people each deposit 1 stETH each, you will
                      get 10% of the MOR tokens for the duration that your stETH is staked.
                    </Text>
                  </Flex>
                  <Alert status='warning' alignItems='flex-start'>
                    <AlertIcon />
                    <Flex flexDir='column'>
                      <AlertTitle>Note</AlertTitle>
                      <AlertDescription fontSize='sm' lineHeight='normal'>
                        During the first 90 days, MOR is not transferable. This means stakers will
                        accumulate a MOR balance, but cannot withdraw it until 90 days. At the 90
                        day point, a liquidity pool for MOR/stETH will be created (on Arbitrum), a
                        market price will be established, and the token will be transferable like
                        normal. This was done to prevent absurd market price on day 1 when supply is
                        negligible.
                      </AlertDescription>
                    </Flex>
                  </Alert>
                </Stack>
              </AccordionPanel>
            </AccordionItem>
            <AccordionItem borderWidth={0} borderBottom={0}>
              <h2>
                <AccordionButton>
                  <Box as='span' flex='1' textAlign='left' fontWeight='bold'>
                    Why does Morpheus want you to stake stETH?
                  </Box>
                  <AccordionIcon />
                </AccordionButton>
              </h2>
              <AccordionPanel pb={4} fontSize='sm'>
                Morpheus gets the stETH yield while you do this. Half of it is traded into MOR, and
                then both halves are held forever as protocol owned liquidity. This will be
                providing a small continual source of demand for MOR, and a growing liquidity pool
                over time.
              </AccordionPanel>
            </AccordionItem>
          </Accordion>
        </Card>
        {data.map(group => {
          return (
            <Card key={group.group}>
              <CardHeader textTransform='uppercase' px={4} fontWeight='bold' color='text.subtle'>
                {group.group}
              </CardHeader>
              <Accordion>
                {group.items.map(item => {
                  return (
                    <AccordionItem key={item.question} borderColor='whiteAlpha.100'>
                      <h2>
                        <AccordionButton>
                          <Box as='span' flex='1' textAlign='left' fontWeight='bold'>
                            {item.question}
                          </Box>
                          <AccordionIcon />
                        </AccordionButton>
                      </h2>
                      <AccordionPanel pb={4} fontSize='sm'>
                        {item.answer}
                      </AccordionPanel>
                    </AccordionItem>
                  )
                })}
              </Accordion>
            </Card>
          )
        })}
      </Stack>
    </PageContainer>
  )
}
